### ISSUE TITLE
fitting an occupation holder class into BFO/OBO and BCIO?

### ISSUE THREAD

**Issue by ddooley** [HumanBehaviourChangeProject/ontologies#328]
I'm wondering about how an occupation holder class, e.g. plumber, architect, hazardous material handler etc. would fit into BFO/OBO and BCIO?  I’m wondering if a combination of BCIO’s [process aggregate](https://www.ebi.ac.uk/ols/ontologies/bcio/terms?iri=http%3A%2F%2Fhumanbehaviourchange.org%2Fontology%2FBCIO_036107) and UBERON (and others) "[processual entity](http://purl.obolibrary.org/obo/UBERON_0000000)" and OBI “has performer” may work?
 
BCIO’s process aggregate idea encompasses more than one process: “Process aggregate extends BFO in the same way that object aggregate extends its coverage of material entities.”

UBERON processual entity (A term that should migrate to COB?): “An occurrent that exists in time by occurring or happening, has temporal parts and always involves and depends on some entity.”
  
OBI has performer  (And we should have OBI add inverse “performer of”?)
 
Then perhaps:

**occupation**: a process aggregate which has as parts processual entities which are occupational services all provided by one performer.

**occupational service**: a processual entity performed by an occupation holder and which [provides outputs to or removes inputs from] some recipient of the service.

**occupation holder**: A material entity which is a “performer of” some occupational service.

An occupation holder could then map to a segment of a human’s (or possibly, funnily enough robot’s) existence. Its awkward dealing with a 3D ontology, but to map “occupation holder” to a human being for some duration(s) of time (akin to a life stage), probably need an object property named something like “congruent with at some time” to enable “occupation holder ‘congruent with at some time’ some Homo Sapiens”. Not sure if something like that exists in RO though?
 
Damion

**Comment by robertjwest** [comment]
Very interesting thoughts. We are treating 'occupation' as 'occupational role' as a subclass of 'role'. But your approach also makes sense. Janna?

**Comment by ddooley** [comment]
Well, things have progressed for an OccO occupation ontology since I wrote that comment, and OccO isn't involving an process aggregate approach.  Instead: https://github.com/Occupation-Ontology/OccO has a role approach which probably aligns with what you have.  I suppose an instance of an occupation could still have a process aggregate to explain what happens during its employ.

**Comment by ddooley** [comment]
Feel free to close this thread here!
